spring:
  application:
    name:
      readyou-back

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: readyou
    region:
      static: ap-southeast-2
    stack:
      auto: false